// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58jYzR-fn9KE1RMYzhvOXAMsJleB-k4c',
    appId: '1:516192225541:web:2547297df8bdd72d554f6c',
    messagingSenderId: '516192225541',
    projectId: 'tennisapp-b7183',
    authDomain: 'tennisapp-b7183.firebaseapp.com',
    storageBucket: 'tennisapp-b7183.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWDdJsegBSn4s7YipNHoSSpvsRSs08FU',
    appId: '1:516192225541:android:b683ab6157c3a04b554f6c',
    messagingSenderId: '516192225541',
    projectId: 'tennisapp-b7183',
    storageBucket: 'tennisapp-b7183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRefDSwtKvCUNDq_LhMpAYhyV_2uRnj28',
    appId: '1:516192225541:ios:29342757860db524554f6c',
    messagingSenderId: '516192225541',
    projectId: 'tennisapp-b7183',
    storageBucket: 'tennisapp-b7183.appspot.com',
    iosBundleId: 'com.example.cleanArchWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRefDSwtKvCUNDq_LhMpAYhyV_2uRnj28',
    appId: '1:516192225541:ios:b2ee23128c000329554f6c',
    messagingSenderId: '516192225541',
    projectId: 'tennisapp-b7183',
    storageBucket: 'tennisapp-b7183.appspot.com',
    iosBundleId: 'com.example.cleanArchWeatherApp.RunnerTests',
  );
}
